name: Build & deploy Shakespeare JSON Viewer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Generate index.json at repo root
      - name: Build index.json
        run: node tools/build-index.mjs

      # Prevent Jekyll processing (not strictly needed with Actions,
      # but harmless and helps if you later switch to “Deploy from a branch”)
      - name: Add .nojekyll
        run: touch .nojekyll

      # Upload the entire repo as the Pages artifact.
      # This keeps all scene JSON files in place so the paths in index.json resolve.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
